import "clWinUIRNA.idl"; 

namespace How2_PartII_DataTemplateSelector
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        clWinUIRNA  GetWinUIRNA_Window_Property{get;};
    
    }
}
