import "clWinUIRNA.idl"; 

namespace How2_DataTemplateSelector
{
    [default_interface]
    runtimeclass clWinUIControl_RNAList : Microsoft.UI.Xaml.Controls.Page
    {
        clWinUIControl_RNAList();
        clWinUIRNA  GetWinUIRNA_Page_Property;
    }
}
